name: Upload dotnet package

on: 
  pull_request:
    types: 
      - closed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/RANDA-Solutions/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
      - name: Setup .NET 8.0 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/RANDA-Solutions/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
      - run: dotnet build --configuration Release OpenCredentialPublisher.Credentials.csproj
      - name: Create the package
        run: dotnet pack --configuration Release OpenCredentialPublisher.Credentials.csproj
      - name: Publish the package to GPR
        run: dotnet nuget push bin/Release/*.nupkg